#include "main_page.hpp"

#include <cstdio>

namespace yzk {

namespace {

struct DemoButton : Button {
    Label* out;
    DemoButton(const String& text, Label* out_label) : Button(text), out(out_label) {}
    void on_click() override {
        char buf[64];
        std::snprintf(buf, sizeof(buf), "button '%s' clicked", text().c_str());
        out->set_text(buf);
    }
};

struct DemoCheckBox : CheckBox {
    Label* out;
    DemoCheckBox(const String& text, Label* out_label) : CheckBox(text), out(out_label) {}
    void on_toggled(bool checked) override {
        char buf[64];
        std::snprintf(buf, sizeof(buf), "checkbox '%s': %s", text().c_str(), checked ? "on" : "off");
        out->set_text(buf);
    }
};

struct DemoToggle : ToggleSwitch {
    Label* out;
    explicit DemoToggle(Label* out_label) : out(out_label) {}
    void on_toggled(bool checked) override {
        char buf[64];
        std::snprintf(buf, sizeof(buf), "switch: %s", checked ? "on" : "off");
        out->set_text(buf);
    }
};

struct DemoRadio : RadioButton {
    Label* out;
    DemoRadio(const String& text, Label* out_label) : RadioButton(text), out(out_label) {}
    void on_toggled(bool checked) override {
        if (checked) {
            char buf[64];
            std::snprintf(buf, sizeof(buf), "radio: '%s' selected", text().c_str());
            out->set_text(buf);
        }
    }
};

struct DemoSlider : Slider {
    Label* out;
    ProgressBar* bar;
    DemoSlider(Label* out_label, ProgressBar* bar_out) : out(out_label), bar(bar_out) {}
    void on_changed(f32 value) override {
        char buf[64];
        std::snprintf(buf, sizeof(buf), "slider: %.0f", value);
        out->set_text(buf);
        if (bar) bar->set_value(value / 100.0f);
    }
};

struct DemoSpinBox : SpinBox {
    Label* out;
    DemoSpinBox(Label* out_label)
        : SpinBox(50.0, 0.0, 100.0, 5.0), out(out_label) {}
    void on_value_changed(f64 value) override {
        char buf[64];
        std::snprintf(buf, sizeof(buf), "spinbox: %.0f", value);
        out->set_text(buf);
    }
};

struct DemoComboBox : ComboBox {
    Label* out;
    DemoComboBox(std::vector<String> items, Label* out_label)
        : ComboBox(std::move(items)), out(out_label) {}
    void on_change(i32 index) override {
        char buf[128];
        std::snprintf(buf, sizeof(buf), "combo: selected #%d = %s", index,
                      selected_text().c_str());
        out->set_text(buf);
    }
};

struct DemoListView : ListView {
    Label* out;
    explicit DemoListView(Label* out_label) : out(out_label) {}
    void on_selected(i32 index) override {
        char buf[128];
        std::snprintf(buf, sizeof(buf), "list: selected #%d = %s", index,
                      text_at(index).c_str());
        out->set_text(buf);
    }
};

// Rows are generated by index on demand; virtualization only fetches visible rows,
// so the full set is never built.
struct DemoSource : ListView::DataSource {
    i32 count() const override { return 10000; }
    String text_at(i32 index) const override {
        char buf[32];
        std::snprintf(buf, sizeof(buf), "row %d", index);
        return buf;
    }
};

struct DemoDelegate : ListView::RowDelegate {
    void draw(ListView& view, PaintContext& ctx, i32 index, const RectF& row_rect) override {
        const Color dot = (index % 3 == 0)   ? Color{0x8a, 0x6d, 0xd8}
                          : (index % 3 == 1) ? Color{0x4c, 0xaf, 0x50}
                                             : Color{0xff, 0xb7, 0x4d};
        ctx.fill_rounded(RectF::make(row_rect.left + 10.0f, row_rect.top + row_rect.height() * 0.5f - 4.0f,
                                     8.0f, 8.0f),
                         dot, 4.0f);
        const RectF tr = RectF::make(row_rect.left + 26.0f, row_rect.top,
                                     row_rect.width() - 36.0f, row_rect.height());
        ctx.draw_text(view.text_at(index), tr,
                      index == view.selected() ? ctx.theme().accent_text : ctx.theme().text,
                      TextAlignH::Left, TextAlignV::Center);
    }
};

Label* section_hint(FlexBox* body, const char* text) {
    auto label = new Label(text);
    label->set_text_role(TextRole::Secondary);
    label->set_small(true);
    label->set_align(TextAlignH::Left, TextAlignV::Center);
    body->append_child(label);
    return label;
}

FlexBox* section_row(FlexBox* body, f32 spacing = 12.0f) {
    auto row = new FlexBox;
    row->set_spacing(spacing);
    body->append_child(row);
    return row;
}

Label* status_label(FlexBox* row) {
    auto label = new Label("-");
    label->set_small(true);
    label->set_align(TextAlignH::Left, TextAlignV::Center);
    row->append_child(label);
    return label;
}

}  // namespace

Widget* make_controls_page(Window& window) {
    (void)window;
    auto root = new DockPanel;

    auto scroll = new ScrollView;
    root->dock(scroll, Dock::Fill);

    auto body = new FlexBox(Orientation::Vertical);
    body->set_padding(24.0f);
    body->set_spacing(8.0f);
    body->set_align_cross(FlexCrossAlign::Stretch);
    scroll->set_content(body);

    auto title = new Label("Controls");
    title->set_bold(true);
    body->append_child(title);

    // Buttons
    section_hint(body, "Button: hover / pressed / disabled, Enter activates");
    {
        auto row = section_row(body);
        auto out = status_label(row);
        auto primary = new DemoButton("Primary", out);
        row->append_child(primary);
        auto secondary = new DemoButton("Secondary", out);
        secondary->set_accent(false);
        row->append_child(secondary);
        auto disabled = new DemoButton("Disabled", out);
        disabled->set_enabled(false);
        row->append_child(disabled);
        auto disabled_secondary = new DemoButton("Disabled 2", out);
        disabled_secondary->set_accent(false);
        disabled_secondary->set_enabled(false);
        row->append_child(disabled_secondary);
    }

    // CheckBox / ToggleSwitch / RadioButton
    section_hint(body, "CheckBox / ToggleSwitch / RadioButton");
    {
        auto row = section_row(body);
        auto out = status_label(row);
        auto cb = new DemoCheckBox("Check me", out);
        row->append_child(cb);
        auto cb2 = new DemoCheckBox("Check me too", out);
        cb2->set_checked(true);
        row->append_child(cb2);
        auto sw = new DemoToggle(out);
        row->append_child(sw);
        auto r1 = new DemoRadio("A", out);
        auto r2 = new DemoRadio("B", out);
        auto r3 = new DemoRadio("C", out);
        row->append_child(r1);
        row->append_child(r2);
        row->append_child(r3);
    }

    // Slider + progress bar
    section_hint(body, "Slider drives ProgressBar (value 0-100)");
    {
        auto row = section_row(body);
        auto out = status_label(row);
        auto slider = new DemoSlider(out, nullptr);
        row->append_child(slider);
        auto bar = new ProgressBar;
        row->append_child(bar);
        slider->bar = bar;
        auto indeterminate = new ProgressBar;
        indeterminate->set_indeterminate(true);
        row->append_child(indeterminate);
    }

    // Text input
    section_hint(body, "TextBox: single line / password / multiline");
    {
        auto row = section_row(body);
        auto single = new TextBox(String(), TextBoxConfig{});
        single->set_placeholder("Type something...");
        row->append_child(single);
        TextBoxConfig pw;
        pw.mode = TextBoxMode::Password;
        auto password = new TextBox(String(), pw);
        password->set_placeholder("password");
        row->append_child(password);
        TextBoxConfig ml;
        ml.mode = TextBoxMode::MultiLine;
        ml.min_lines = 3;
        auto multiline = new TextBox("line one\nline two", ml);
        row->append_child(multiline);
    }

    // Numeric input
    section_hint(body, "SpinBox (0-100, step 5)");
    {
        auto row = section_row(body);
        auto out = status_label(row);
        auto spin = new DemoSpinBox(out);
        row->append_child(spin);
    }

    // Dropdown
    section_hint(body, "ComboBox");
    {
        auto row = section_row(body);
        auto out = status_label(row);
        auto combo = new DemoComboBox({"Alpha", "Beta", "Gamma", "Delta"}, out);
        row->append_child(combo);
    }

    // List
    section_hint(body, "ListView: 20 items, scrollable");
    {
        auto row = section_row(body);
        auto out = status_label(row);
        row->append_child(out);
        auto list = new DemoListView(out);
        std::vector<String> items;
        for (int i = 0; i < 20; ++i) items.push_back("item " + std::to_string(i));
        list->set_items(items);
        list->set_max_height(200.0f);
        row->append_child(list);
    }

    // Virtualized large list
    section_hint(body, "ListView: 10000 rows via DataSource + custom row delegate");
    {
        auto row = section_row(body);
        auto out = status_label(row);
        row->append_child(out);
        static DemoSource src;
        static DemoDelegate delegate;
        auto list = new DemoListView(out);
        list->set_data_source(&src);
        list->set_row_delegate(&delegate);
        list->set_max_height(200.0f);
        row->append_child(list);
    }

    return root;
}

}  // namespace yzk